### ISSUE TITLE
Allow ttl to be set as string

### ISSUE THREAD

**Issue by azachar** [nodevault/node-vault#139]
Hello,
based on the documentation https://www.vaultproject.io/api/auth/approle/index.html#token_ttl
you can specify integer or string, 

but you scheme restrict this only to integers:
https://github.com/kr1sp1n/node-vault/blob/c1d91b9973c0f02256112bed02cf8c4c7c5d5a31/src/commands.js#L1002

Could you please change that to string? Thank you.

**Comment by aviadhahami** [comment]
@azachar feel free to PR this :) 
Closing for the meantime

feature request ---> Parse TTL strings and allow `string` type for TTL
