### ISSUE TITLE
Replacing Request with another library

### ISSUE THREAD

**Issue by pratikpc** [nodevault/node-vault#150]
As of https://github.com/request/request/issues/3142, the Request Library and Request-Promise library on which Node-Vault depend, have both been deprecated

As such, I believe that, we must replace Request with another library
The async libraries which could replace it are
1. [Node-Fetch](https://www.npmjs.com/package/node-fetch)
2. [Axios](https://www.npmjs.com/package/axios)
3. Any Other ??

**Comment by bjankord** [comment]
It would be nice to find an alternative for request. There is a thread on https://github.com/request/request/issues/3143 about alternatives.

**Comment by pratikpc** [comment]
@bjankord I tried my hand at replacing Request with axios in this [pull request](https://github.com/kr1sp1n/node-vault/pull/151)

Let's see if it's accepted

**Comment by fungiboletus** [comment]
A good alternative to request is [`got`](https://github.com/sindresorhus/got) IMHO.

**Comment by muturgan** [comment]
> @bjankord I tried my hand at replacing Request with axios in this [pull request](https://github.com/kr1sp1n/node-vault/pull/151)
> 
> Let's see if it's accepted

axios is amasing

**Comment by aviadhahami** [comment]
I'd like to budge in and offer [needle](https://www.npmjs.com/package/needle)

**Comment by delfuego** [comment]
For me, the prime driver for replacing `request` is that it brings along **20 additional dependencies** that are almost certainly not needed by upstream projects.
Given that there was a pull request to move to axios submitted above, is there any way to nudge this along? It would be really great to resolve this one.

**Comment by jjnkr** [comment]
This issue is affecting me as well, because having `request-promise` and `request-promise-native` in the dependency tree causes problems when testing with Jest: https://github.com/request/request-promise/issues/247

Is there any way to help the axios PR along?

**Comment by adam2k** [comment]
It seems like this PR was opened over a year ago. Is this project no longer maintained and are there alternatives?

**Comment by aviadhahami** [comment]
@adam2k seems so [unmaintained]

**Comment by tgrassl** [comment]
@kr1sp1n Any updates on this?

**Comment by adam2k** [comment]
@aviadhahami do you know of any other good alternatives and is it worth forking this repo at this point?

**Comment by aviadhahami** [comment]
@adam2k  - per "is it worth" --> there are 52K downloads per week of this pkg (according to [npm](https://www.npmjs.com/package/node-vault))

@pratikpc , regarding https://github.com/kr1sp1n/node-vault/pull/151, any progress? the last comment was asking to fix the conflicts. Can you attend this? (if not - I believe others [including myself] are able to help :) )

**Comment by adam2k** [comment]
@aviadhahami I'm unfamiliar with the npm process of forking a project like this.  I suppose we could fork and make a new project that is open sourced.  I'll talk with my company about working on a project like this to see if I can get support from them as well.

**Comment by aviadhahami** [comment]
@adam2k not sure myself as well, I think we can maintain this if you'd like :)
@kr1sp1n - is this 100% stale on your end? if yes - would u like to move ownership to @adam2k & myself?

**Comment by aviadhahami** [comment]
Update - emailed `npm` themselves for a dispute on package name due to owner's inactivity and the security risk imposed by this

**Comment by kr1sp1n** [comment]
@aviadhahami Hi, I would like to move the ownership to you. I do not maintain this lib any longer but I would love to hand it over to responsible people. Let me know where to move it exactly.

**Comment by aviadhahami** [comment]
Hi @kr1sp1n, thx for the reply :)

Steps needs to be taken:
1/ Change npm ownership [[howto]](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) [[my npm profile]](https://www.npmjs.com/~uiw4nk3r)
2/ Change GH ownership [[howto]](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) [[my gh profile]](https://github.com/aviadhahami/)

IMO that's it.
lmk if u need any help or anything :)

**Comment by adam2k** [comment]
Thanks @kr1sp1n and @aviadhahami! 👍🏻

**Comment by adam2k** [comment]
@aviadhahami and @kr1sp1n let me know if you all need anything from me in the immediate term.  Otherwise I'll open up PRs in @aviadhahami's repo when it's ready to go.

**Comment by pratikpc** [comment]
Hey guys I think the safest option is Postman Request.

Asio would be a bit of a headache to port as I found out myself and would definitely break existing code for users so we can move to Postman Request for the time being.

Postman Request is the request we love and admire (I don't) with the bugs fixed and slightly less warnings
I was also able to update a lot of the codebase and dependencies and fix code with the newer changes as recommended by our Airbnb overlords with a few ignored

**Comment by adam2k** [comment]
@aviadhahami and @kr1sp1n do you all have an idea when this repo could be transferred?

**Comment by aviadhahami** [comment]
@adam2k I'm waiting patiently 🤷‍♂️

**Comment by kr1sp1n** [comment]
@adam2k @aviadhahami  I added @aviadhahami to the npm maintainers, created a github organization called "nodevault" (node-vault was already taken) and invited @aviadhahami as a member. That should do the trick, right?

**Comment by aviadhahami** [comment]
@kr1sp1n almost :D 
I still lack permissions and get this:
<img width="653" alt="image" src="https://user-images.githubusercontent.com/7353632/155543726-bb0ec883-fd1c-4d2a-8555-fb2654079899.png">


So, what's left to do is:
1/ give repo permissions
2/ give npm permissions (for publishing)

**Comment by aviadhahami** [comment]
@kr1sp1n pinging again (so we can stop ping you <3 )
lmk if u wanna zoom on this so we can tie all ends and get it over with :)

**Comment by xenoterracide** [comment]
has someone forked? as far as github just fork (could do as not even a "click fork", just clone and push to a new repo), npm rights are more important, as to update all of the info.

**Comment by mmt-trackunit** [comment]
@kr1sp1n was the missing ownership ever resolved?

**Comment by aviadhahami** [comment]
@kr1sp1n added me to the org so I can collab, but I still lack permissions to the repo 😕
<img width="141" alt="image" src="https://user-images.githubusercontent.com/7353632/200865632-6ca4f377-fa05-419f-8676-4eda92d76ca6.png">

_Siri, play "we're half way there"_

**Comment by aviadhahami** [comment]
@kr1sp1n, please, if you can clear up an hour (±) we can do a handover and I can help maintain 🙏

**Comment by kr1sp1n** [comment]
@aviadhahami I gave you maintainer role of this repo now. Sorry for the late reply 🙄 If you have any questions then we could have a chat, of course.

**Comment by vetlevo** [comment]
@kr1sp1n & @aviadhahami, how's it going with getting access to publish new versions to NPM? 😊

**Comment by aviadhahami** [comment]
@vetlevo Unfortunately I can't deploy to `npm` as I don't have the keys (nor there's any CI process for that)

We need to keep pinging @kr1sp1n for that I guess :\

**Comment by ziermach** [comment]
@kr1sp1n i also wait for that new version

**Comment by rampandu69701** [comment]
@kr1sp1n I am also waiting for that new version.

**Comment by atre** [comment]
@kr1sp1n please help with this issue

**Comment by Wojciechowski-Marcin** [comment]
Any updates on this topic?

**Comment by aviadhahami** [comment]
Hey @Wojciechowski-Marcin  - I currently can't find the time for the fix.
I did some job around the project thus far so anyone can contribute easily.
Feel free to help out <3

**Comment by aviadhahami** [comment]
Hi everyone!
Release v.0.10.0 is out with a new HTTP lib and all the recent commits (where recent is ~2 years 😮 )
Closing :D
