### ISSUE TITLE
Snyk issue found in request-promise-native dependency on lodash@4.17.19

### ISSUE THREAD

**Issue by matt-primrose** [nodevault/node-vault#167]
Hello @kr1sp1n 

We're seeing Snyk reporting an issue with one of your dependencies (request-promise-native@1.0.7).  Looking at request-promise-native it looks like that library has been deprecated and will no longer be updated (a list of alternatives is provided on their github page).  Do you have a path to resolving this in the near future?  We'd like to continue using your library as our interface point for Vault, but need to have clean Snyk scans for our customers.

Looking forward to your reply.

**Comment by rsdmike** [comment]
Related to #150
