### ISSUE TITLE
Implement /sys/tools functions (Random Bytes and Hashing)

### ISSUE THREAD

**Issue by nickdaugherty** [nodevault/node-vault#178]
Vault has `/sys/tools/random/:bytes` and `/sys/tools/hash/:algorithm` endpoints that can be implemented with helper functions.

https://www.vaultproject.io/api-docs/system/tools#generate-random-bytes

**Comment by aviadhahami** [comment]
Hey @nickdaugherty - do you mind PRing this? :) that could be awesome

Closing the ticket for now due to staleness


Feature request --> support random bytes generation endpoints
