### ISSUE TITLE
Vulnerability in sub-dependency json-schema

### ISSUE THREAD

**Issue by OlikPolik** [nodevault/node-vault#192]
Version of request package you are using has a json-schema sub-dependency which is version 0.2.3 which now has an official vulnerability. Is there any chance you could bump up request version or json-schema version?

Thanks

**Comment by delfuego** [comment]
My guess is that this is going to be stuck in the same state as #150 — it doesn't look like node-vault is being maintained anymore, so this won't get fixed. We'll see.

**Comment by HappyZombies** [comment]
They can't resolve this cuz the dependency is within the 'request' module which that itself doesn't even have the fix/latest version of 'http-signature'. This vulnerability goes a little deep.

See https://github.com/request/request/issues/3394

**Comment by aviadhahami** [comment]
Heya folks! 
I'm a new maintainer here (outcome of #150)
Will work to resolve the vulnerability soon!
