### ISSUE TITLE
unable to write new secrets

### ISSUE THREAD

**Issue by Dayo-Adewuyi** [nodevault/node-vault#212]
i tried to write a secret to vault using the code below

`await vault.write('secret/hello', { value: 'world', lease: '1s' })` but i keep getting the error ` response: { statusCode: 400, body: { errors: [ 'no data provided' ] } }`

**Comment by jerryk1925** [comment]
You fix this problem?

**Comment by codinger41** [comment]
@Dayo-Adewuyi how did you resolve this please?

**Comment by joacoc** [comment]
@codinger41 prepending `{ data: ... }` solved the issue for me

example `await vault.write('secret/hello', { data: { value: 'world', lease: '1s' }})`
