### ISSUE TITLE
Transit secret

### ISSUE THREAD

**Issue by wzalazar** [nodevault/node-vault#73]
Hi, I'm trying implement Vault in my project. So, I need to implement transit secret. I don't find any example. Can you help me?

I leave the link about that, https://www.vaultproject.io/docs/secrets/transit/

Is it possible?

**Comment by DaniGuardiola** [comment]
There is an [API](https://www.vaultproject.io/api/secret/transit/index.html) for that, so it is possible. @kr1sp1n I would add a to-do label to it. BTW, any chance you could add me as a collaborator so I can manipulate and manage bugs, milestones and PRs? :) Obviously I won't do anything without the proper code reviews and stuff

**Comment by brandonros** [comment]
https://github.com/kr1sp1n/node-vault/pull/96

**Comment by mkhraisha** [comment]
is there support for the transit encrypt endpoints?

**Comment by aviadhahami** [comment]
@mkhraisha not atm, but feel free to PR this :)

**Comment by EvanTedesco** [comment]
> @mkhraisha not atm, but feel free to PR this :) [ ps - take a look here #96 ]
> 
> Closing for now :)

@wzalazar I see this PR: https://github.com/nodevault/node-vault/pull/115 that says it adds transit/database support.  I have just validated it locally as well.
