### ISSUE TITLE
Authentication Backends Cannot Create Root Tokens

### ISSUE THREAD

**Issue by a-cabinti** [nodevault/node-vault#79]
Hi,

I need to get my secret on my separate host vault server setup but after I perform vault.userpassLogin({ username, password }) I got this error. 

(node:33152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: authentication backends cannot create root tokens

**Comment by DaniGuardiola** [comment]
Hi, that message is being returned from the vault endpoint, so it is not a `node-vault` issue. The Vault API is returning that error. Your request must be wrong.

By the way, I recommend you add a `.catch(console.error)` at the end of your promise chain to correctly catch and log the errors (and avoid those nasty `UnhandledPromiseRejectionWarning` logs).

Good luck with your debugging :)

@kr1sp1n I think you should close this

**Comment by DaniGuardiola** [comment]
Ah, this might be related to #66

**Comment by aviadhahami** [comment]
Stale issue that's [maybe] related to #66; Closing for now
