### ISSUE TITLE
Connect to a HA vault

### ISSUE THREAD

**Issue by TinOo512** [nodevault/node-vault#95]
In an HA environment we will have multiple node (ex. ` https://a.vault.mycompany.com:8200`, ` https://b.vault.mycompany.com:8200`, ...). Because that library support only one endpoint I'm wondering what's the best practice here?

- Should endpoint support an array of nodes where we replay the request to another node in case of a failure? 
- According to https://www.vaultproject.io/docs/concepts/ha.html#behind-load-balancers a load balancer isn't the best solution, ...
- Round robin DNS?
- Should we install the vault agent locally and use `https://localhost:8200` as endpoint?

Thanks!

**Comment by aviadhahami** [comment]
feature-request --> allow node rotation if request failed
